TCP_CONTROL_PORT    = 9000
UDP_FRAME_PORT      = 9001

FRAME_RATE_CAP      = 20
JPEG_QUALITY        = 60
FRAME_QUEUE_MAXSIZE = 1

MIN_BOUNDARY_POINTS = 4
MIN_AREA_M2         = 0.5
WALL_HEIGHT         = 2.0

EMA_ALPHA           = 0.35
VOTE_WINDOW         = 7
VOTE_THRESHOLD      = 5

COOLDOWN_PINCH      = 1.2
COOLDOWN_FIST       = 2.0
COOLDOWN_OPEN_PALM  = 0.8

HAND_DETECT_CONF    = 0.70
HAND_TRACK_CONF     = 0.60
HAND_PRESENCE_CONF  = 0.70

POINT_EXTENDED_MIN  = 0.6
POINT_CURLED_MAX    = 0.5

PROXIMITY_WARN_DIST = 0.5
HAPTIC_DIST         = 0.25