TCP_CONTROL_PORT    = 9000
UDP_FRAME_PORT      = 9001

FRAME_RATE_CAP      = 15
JPEG_QUALITY        = 45
FRAME_QUEUE_MAXSIZE = 1

MIN_BOUNDARY_POINTS = 4
MIN_AREA_M2         = 0.5
WALL_HEIGHT         = 2.0

EMA_ALPHA           = 0.45

# Faster but still stable enough for gestures.
VOTE_WINDOW         = 5
VOTE_THRESHOLD      = 3

COOLDOWN_PINCH      = 0.45
COOLDOWN_FIST       = 1.20
COOLDOWN_OPEN_PALM  = 0.45

HAND_DETECT_CONF    = 0.55
HAND_TRACK_CONF     = 0.50
HAND_PRESENCE_CONF  = 0.55

POINT_EXTENDED_MIN  = 0.62
POINT_CURLED_MAX    = 0.52

# Custom landmark gesture thresholds.
PINCH_MAX_RATIO     = 0.46
PINCH_INDEX_MIN_RATIO = 0.22
OPEN_EXTEND_MARGIN  = 0.08
FIST_TIP_MCP_MAX_RATIO = 0.72

PROXIMITY_WARN_DIST = 0.5
HAPTIC_DIST         = 0.25